USE [master]
GO
/****** Object:  Database [IOT]    Script Date: 17-04-2018 13:10:06 ******/
CREATE DATABASE [IOT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IOT', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\IOT.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'IOT_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\IOT_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [IOT] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [IOT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [IOT] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [IOT] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [IOT] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [IOT] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [IOT] SET ARITHABORT OFF 
GO
ALTER DATABASE [IOT] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [IOT] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [IOT] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [IOT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [IOT] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [IOT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [IOT] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [IOT] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [IOT] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [IOT] SET  DISABLE_BROKER 
GO
ALTER DATABASE [IOT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [IOT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [IOT] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [IOT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [IOT] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [IOT] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [IOT] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [IOT] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [IOT] SET  MULTI_USER 
GO
ALTER DATABASE [IOT] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [IOT] SET DB_CHAINING OFF 
GO
ALTER DATABASE [IOT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [IOT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [IOT] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [IOT] SET QUERY_STORE = OFF
GO
USE [IOT]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [IOT]
GO
/****** Object:  User [IIS APPPOOL\Training AppPool]    Script Date: 17-04-2018 13:10:06 ******/
CREATE USER [IIS APPPOOL\Training AppPool] FOR LOGIN [IIS APPPOOL\Training AppPool] WITH DEFAULT_SCHEMA=[dbo]
GO
ALTER ROLE [db_owner] ADD MEMBER [IIS APPPOOL\Training AppPool]
GO
/****** Object:  Table [dbo].[Attendance]    Script Date: 17-04-2018 13:10:06 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Attendance](
	[UniqueId] [int] IDENTITY(1,1) NOT NULL,
	[StudentId] [bigint] NULL,
	[SchoolId] [int] NULL,
	[StudentName] [varchar](60) NULL,
	[ClassName] [varchar](30) NULL,
	[IsPresent] [bit] NULL,
	[IsParentNotified] [bit] NULL,
	[AttendanceDate] [datetime] NULL,
	[ParentId] [bigint] NULL,
	[ParentName] [varchar](60) NULL,
	[TeacherId] [bigint] NULL,
	[TeacherName] [varchar](60) NULL,
	[TermId] [int] NULL,
 CONSTRAINT [PK_Attendance] PRIMARY KEY CLUSTERED 
(
	[UniqueId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Student]    Script Date: 17-04-2018 13:10:07 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Student](
	[StudentId] [bigint] NOT NULL,
	[Name] [varchar](60) NULL,
	[ParentPhone] [varchar](20) NULL,
	[ParentEmail] [varchar](50) NULL,
	[ParentName] [varchar](60) NULL,
 CONSTRAINT [PK_Student] PRIMARY KEY CLUSTERED 
(
	[StudentId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [IOT] SET  READ_WRITE 
GO
